version: "3.9"

services:
  web:
    build: .
    container_name: django_ip_tracker
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend_security.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: postgres_ip_tracker
    environment:
      POSTGRES_DB: iptracker
      POSTGRES_USER: ipuser
      POSTGRES_PASSWORD: ippassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis_ip_tracker
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
